### ISSUE TITLE
/WEB-INF/pages/header.jsp not found

### ISSUE THREAD

**Issue by lozybean** [reactome/content-service#1]
run 

```
mvn tomcat7:run -D... 
```

then view on browser: http://localhost:8686, there throws out en exception:

`javax.servlet.ServletException: File &quot;/WEB-INF/pages/header.jsp&quot; not found`

there's no header.jsp in WEB-INF dir, is the file missing?

**Comment by lozybean** [comment]
It looks like the error caused by the template server "http://reactomedev.oicr.on.ca/" being unreachable

**Comment by gsviteri** [comment]
@lozybean it might be too late to reply to your comment. I do apologise for that. I am going to post the solution.
You can use our dev server as a template server: https://dev.reactome.org. 
Another solution: install our Joomla [Website](https://github.com/reactome/Website) on your computer or local server and use localhost as a template-server.
Thanks
